import React, { useState } from 'react';
import { Trash2, CheckCircle2, Sun, Moon, Download, FileText, Palette, Coins } from 'lucide-react';
import { Currency, ThemeMode } from '../types';
import { generatePdfReport } from '../utils/pdfExport';

interface SettingsTabProps {
  currency: Currency;
  onCurrencyChange: (c: Currency) => void;
  onClearAll: () => void;
  theme?: ThemeMode;
  onToggleTheme?: () => void;
}

export const SettingsTab: React.FC<SettingsTabProps> = ({
  currency = 'INR',
  onCurrencyChange,
  onClearAll,
  theme = 'dark',
  onToggleTheme,
}) => {
  const [clearedNotice, setClearedNotice] = useState<boolean>(false);
  const [exportNotice, setExportNotice] = useState<boolean>(false);
  const [showConfirmModal, setShowConfirmModal] = useState<boolean>(false);

  const handleResetData = () => {
    onClearAll();
    setShowConfirmModal(false);
    setClearedNotice(true);
    setTimeout(() => setClearedNotice(false), 3000);
  };

  const handleExportAllToPDF = () => {
    try {
      const savedHistory = localStorage.getItem('calculator_hub_calc_history');
      const historyList = savedHistory ? JSON.parse(savedHistory) : [];

      const rows: string[][] = [];

      if (historyList.length > 0) {
        historyList.forEach((item: any, idx: number) => {
          rows.push([
            `Calc #${idx + 1}`,
            item.timestamp || 'N/A',
            'Standard Math',
            item.expression || '',
            item.result || '',
          ]);
        });
      } else {
        rows.push(['Sample Entry', new Date().toLocaleDateString(), 'App Setup', 'Initialization', 'Success']);
      }

      generatePdfReport({
        title: 'Offline Calculator Session Records Summary',
        subtitle: `Complete exported activity records for offline storage`,
        metrics: [
          { label: 'Total Saved Logs', value: String(historyList.length) },
          { label: 'Export Date', value: new Date().toLocaleDateString() },
          { label: 'Active Currency', value: String(currency), isHighlight: true },
        ],
        tableHeaders: ['Record ID', 'Timestamp', 'Category', 'Expression / Inputs', 'Output Result'],
        tableRows: rows,
        notes: 'Generated by Calculator Hub Calculator Engine.',
      });

      setExportNotice(true);
      setTimeout(() => setExportNotice(false), 3000);
    } catch {
      // ignore
    }
  };

  return (
    <div className="max-w-md mx-auto space-y-5 text-white pb-24 px-3 pt-2">
      {/* Title */}
      <h1 className="text-xl font-bold text-center text-white tracking-tight">Settings</h1>

      {clearedNotice && (
        <div className="bg-orange-950/80 border border-orange-800 text-orange-300 p-3 rounded-xl text-xs font-semibold flex items-center space-x-2 animate-in fade-in">
          <CheckCircle2 className="w-4 h-4 text-orange-400 shrink-0" />
          <span>All saved calculator state, history, and preferences have been deleted.</span>
        </div>
      )}

      {exportNotice && (
        <div className="bg-orange-950/80 border border-orange-800 text-orange-300 p-3 rounded-xl text-xs font-semibold flex items-center space-x-2 animate-in fade-in">
          <CheckCircle2 className="w-4 h-4 text-orange-400 shrink-0" />
          <span>Exported calculation results to PDF successfully!</span>
        </div>
      )}

      {/* SECTION: APPEARANCE & THEME */}
      <div className="space-y-2">
        <h2 className="text-[11px] font-bold text-gray-400 tracking-wider uppercase px-1 flex items-center space-x-1.5">
          <Palette className="w-3.5 h-3.5 text-orange-400 dark:text-emerald-400" />
          <span>Appearance & Theme</span>
        </h2>

        <div className="bg-[#121215] border border-gray-800/90 rounded-2xl p-4 space-y-3 shadow-xl">
          <p className="text-xs text-gray-400">
            Default theme is set to Dark mode upon opening. Switch theme below anytime:
          </p>

          <div className="grid grid-cols-2 gap-3 pt-1">
            <button
              onClick={() => {
                if (theme !== 'dark' && onToggleTheme) onToggleTheme();
              }}
              className={`p-3 rounded-xl border text-left flex flex-col justify-between space-y-2 cursor-pointer transition-all ${
                theme === 'dark'
                  ? 'bg-black border-emerald-500 text-white shadow-md ring-2 ring-emerald-500/30'
                  : 'bg-white border-slate-200 text-slate-700 hover:border-slate-300 shadow-xs'
              }`}
            >
              <div className="flex items-center justify-between">
                <Moon className={`w-4 h-4 ${theme === 'dark' ? 'text-emerald-400' : 'text-slate-500'}`} />
                {theme === 'dark' && (
                  <span className="text-[10px] font-bold text-emerald-400 bg-emerald-500/20 px-2 py-0.5 rounded-full">
                    Active
                  </span>
                )}
              </div>
              <div>
                <span className={`text-xs font-extrabold block ${theme === 'dark' ? 'text-white' : 'text-slate-900'}`}>
                  Deep Dark
                </span>
                <span className={`text-[10px] ${theme === 'dark' ? 'text-gray-400' : 'text-slate-500'}`}>
                  Obsidian & Classic Green
                </span>
              </div>
            </button>

            <button
              onClick={() => {
                if (theme !== 'light' && onToggleTheme) onToggleTheme();
              }}
              className={`p-3 rounded-xl border text-left flex flex-col justify-between space-y-2 cursor-pointer transition-all ${
                theme === 'light'
                  ? 'bg-white border-2 border-orange-500 text-slate-900 shadow-md ring-2 ring-orange-500/30'
                  : 'bg-[#1a1a1e] border-gray-800 text-gray-400 hover:border-gray-700'
              }`}
            >
              <div className="flex items-center justify-between">
                <Sun className={`w-4 h-4 ${theme === 'light' ? 'text-orange-500' : 'text-gray-500'}`} />
                {theme === 'light' && (
                  <span className="text-[10px] font-bold text-orange-700 bg-orange-100 px-2 py-0.5 rounded-full">
                    Active
                  </span>
                )}
              </div>
              <div>
                <span className={`text-xs font-extrabold block ${theme === 'light' ? 'text-slate-900' : 'text-gray-200'}`}>
                  Sophisticated Light
                </span>
                <span className={`text-[10px] ${theme === 'light' ? 'text-slate-600' : 'text-gray-400'}`}>
                  Orange & White
                </span>
              </div>
            </button>
          </div>
        </div>
      </div>

      {/* SECTION: CURRENCY PREFERENCE */}
      <div className="space-y-2">
        <h2 className="text-[11px] font-bold text-gray-400 tracking-wider uppercase px-1 flex items-center space-x-1.5">
          <Coins className={`w-3.5 h-3.5 ${theme === 'light' ? 'text-orange-500' : 'text-emerald-400'}`} />
          <span>Currency Preference</span>
        </h2>

        <div className="bg-[#121215] border border-gray-800/90 rounded-2xl p-4 space-y-3 shadow-xl">
          <p className="text-xs text-gray-400">
            Select the active currency symbol used across all investment and loan calculators:
          </p>

          <div className="grid grid-cols-2 gap-2.5 pt-1">
            {[
              { code: 'INR', label: '₹ INR (Indian Rupee)' },
              { code: 'USD', label: '$ USD (US Dollar)' },
              { code: 'EUR', label: '€ EUR (Euro)' },
              { code: 'GBP', label: '£ GBP (British Pound)' },
              { code: 'JPY', label: '¥ JPY (Japanese Yen)' },
              { code: 'CNY', label: '¥ CNY (Chinese Yuan)' },
            ].map((item) => {
              const isSelected = currency === item.code;
              return (
                <button
                  key={item.code}
                  onClick={() => onCurrencyChange(item.code as Currency)}
                  className={`py-2.5 px-3 rounded-xl border text-xs font-bold transition-all cursor-pointer flex items-center justify-between ${
                    theme === 'light'
                      ? isSelected
                        ? 'bg-white border-2 border-orange-500 text-slate-900 shadow-md ring-2 ring-orange-500/30'
                        : 'bg-white border-slate-200 text-slate-700 hover:border-orange-300 hover:bg-orange-50/50 hover:text-slate-900 shadow-xs'
                      : isSelected
                      ? 'bg-black border-emerald-500 text-white shadow-md ring-2 ring-emerald-500/30'
                      : 'bg-[#1a1a1e] border-gray-800 text-gray-400 hover:border-gray-700 hover:text-gray-200'
                  }`}
                >
                  <span className={theme === 'light' && isSelected ? 'text-slate-900 font-extrabold' : ''}>
                    {item.label}
                  </span>
                  {isSelected && (
                    <span
                      className={`w-2 h-2 rounded-full shrink-0 ${
                        theme === 'light'
                          ? 'bg-orange-500 ring-2 ring-orange-200'
                          : 'bg-emerald-400 ring-2 ring-emerald-950'
                      }`}
                    ></span>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* SECTION: EXPORT DATA */}
      <div className="space-y-2">
        <h2 className="text-[11px] font-bold text-gray-400 tracking-wider uppercase px-1 flex items-center space-x-1.5">
          <FileText className="w-3.5 h-3.5 text-orange-400" />
          <span>Offline Records Export</span>
        </h2>

        <div className="bg-[#121215] border border-gray-800/90 rounded-2xl p-4 space-y-3 shadow-xl text-xs">
          <p className="text-gray-300">
            Download your current calculation results and saved history as a clean, branded PDF report summary for offline viewing or printing.
          </p>

          <button
            onClick={handleExportAllToPDF}
            className="w-full inline-flex items-center justify-center space-x-2 py-2.5 px-4 bg-orange-500 hover:bg-orange-400 text-white rounded-xl text-xs font-extrabold transition-all cursor-pointer shadow-md active:scale-95 shadow-orange-500/20"
          >
            <Download className="w-3.5 h-3.5 text-white" />
            <span>Export Calculation Results (PDF Report)</span>
          </button>
        </div>
      </div>

      {/* SECTION 1: APP */}
      <div className="space-y-2">
        <h2 className="text-[11px] font-bold text-gray-400 tracking-wider uppercase px-1">
          APP INFO
        </h2>

        <div className="bg-[#121215] border border-gray-800/90 rounded-2xl p-4 divide-y divide-gray-800/70 shadow-xl text-xs">
          <div className="flex items-center justify-between py-2.5">
            <span className="text-gray-200 font-medium">App name</span>
            <span className="text-gray-400 font-mono">Calculator Hub</span>
          </div>

          <div className="flex items-center justify-between py-2.5">
            <span className="text-gray-200 font-medium">Version</span>
            <span className="text-gray-400 font-mono">1</span>
          </div>

          <div className="flex items-center justify-between py-2.5">
            <span className="text-gray-200 font-medium">Currency</span>
            <span className="text-orange-400 font-mono font-bold">{currency}</span>
          </div>

          <div className="flex items-center justify-between py-2.5">
            <span className="text-gray-200 font-medium">Active Theme</span>
            <span className="text-orange-400 dark:text-emerald-400 font-mono font-bold capitalize">
              {theme === 'dark' ? 'Deep Dark (Obsidian & Warm Green)' : 'Sophisticated Light (Orange)'}
            </span>
          </div>
        </div>
      </div>

      {/* SECTION 3: ABOUT */}
      <div className="space-y-2">
        <h2 className="text-[11px] font-bold text-gray-400 tracking-wider uppercase px-1">
          ABOUT
        </h2>

        <div className="bg-[#121215] border border-gray-800/90 rounded-2xl p-4 space-y-3 shadow-xl text-xs text-gray-300 leading-relaxed">
          <p>
            Calculator Hub bundles a scientific calculator, a unit converter, and a full suite of personal finance and budgeting calculators in one app.
          </p>
          <p className="text-gray-400 text-[11px] leading-normal pt-1 border-t border-gray-800/60">
            All financial figures are estimates based on the rates you enter — not investment advice. Currency conversion rates are approximate reference values, not live market rates.
          </p>
        </div>
      </div>

      {/* Reset Data Option */}
      <div className="pt-2">
        <button
          onClick={() => setShowConfirmModal(true)}
          className={`w-full flex items-center justify-center space-x-2 py-2.5 px-4 rounded-xl text-xs font-bold transition-all cursor-pointer shadow-md active:scale-95 ${
            theme === 'light'
              ? 'bg-red-50 hover:bg-red-100 border border-red-200 text-red-700 shadow-xs'
              : 'bg-red-950/40 hover:bg-red-900/50 border border-red-900/60 text-red-400 hover:text-red-300'
          }`}
        >
          <Trash2 className="w-3.5 h-3.5" />
          <span>Reset All Saved State & Delete Data</span>
        </button>
      </div>

      {/* Confirmation Modal */}
      {showConfirmModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in">
          <div className="bg-[#121215] border border-red-900/60 rounded-2xl max-w-sm w-full p-5 space-y-4 shadow-2xl animate-in zoom-in-95">
            <div className="flex items-center space-x-3 text-red-400">
              <div className="p-2 bg-red-950/80 rounded-xl border border-red-800">
                <Trash2 className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-black text-white">Clear All Data & Settings?</h3>
                <p className="text-[11px] text-gray-400">This action cannot be undone.</p>
              </div>
            </div>

            <p className="text-xs text-gray-300 leading-relaxed bg-black/40 p-3 rounded-xl border border-gray-800">
              This will permanently delete your saved calculation history, stored custom inputs, and preferences. Are you sure you want to proceed?
            </p>

            <div className="flex items-center space-x-2 pt-2 justify-end">
              <button
                type="button"
                onClick={() => setShowConfirmModal(false)}
                className="px-4 py-2 rounded-xl text-xs font-bold text-gray-300 bg-gray-800 hover:bg-gray-700 border border-gray-700 cursor-pointer transition-all"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleResetData}
                className="px-4 py-2 rounded-xl text-xs font-bold text-white bg-red-600 hover:bg-red-500 border border-red-500 cursor-pointer transition-all shadow-lg shadow-red-600/30"
              >
                Yes, Clear All
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
